image: golang:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - mkdir -p bot
    - go build -o bot/whatsapbot ./...
  artifacts:
    paths:
      - bot/whatsapbot

deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - scp bot/whatsapbot $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH && chmod +x whatsapbot && ./whatsapbot"
  environment: production
