image: golang:1.22

stages:
  - build
  - test
  - deploy

variables:
  # Variabel lingkungan untuk konfigurasi deployment
  SSH_PRIVATE_KEY: "<isi dengan kunci pribadi SSH Anda>"
  DEPLOY_SERVER: "128.199.76.91"
  DEPLOY_USER: "root"
  DEPLOY_PATH: "/home/peratan/bot-whatsapp/"

build:
  stage: build
  script:
    - go mod download
    - go build -o myapp .

test:
  stage: test
  script:
    - go test ./...

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
  script:
    - scp myapp $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH && ./myapp"
