# Menentukan tahapan untuk pipeline
stages:
  - build
  - deploy

# Skrip sebelum tahapan untuk menyiapkan kunci SSH untuk deploy
before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts  # Menambahkan -H untuk format output yang benar

# Tahapan build untuk mengompilasi aplikasi Go
build:
  stage: build
  image: golang:1.22
  script:
    - go mod download
    - go build -o myapp

# Tahapan deploy untuk mentransfer aplikasi yang sudah dibangun dan menjalankannya di server
deploy:
  stage: deploy
  script:
    - scp -i ~/.ssh/id_rsa myapp $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
    - ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH && ./myapp"
